### ISSUE TITLE
atm isnt working

### ISSUE THREAD

**Issue by JayGamingX** [GhostgamesDHG/MinetopiaMod#4]
hello i wanted to try atm but it didnt worked could you fix it? :)

**Comment by GhostgamesDHG** [comment]
hello JayGamingX, Thank you for using my mod! I didn't work on the ATM just yet. I have a Idea how I want to do it, but I will focus on the vending machine and the computer first. Then I will make the ATM work. 

If you have any ideas of what the ATM can do, let me know. Then I can maybe implement it. I'm always open for feedback.

Are there other thing you want into the mod, such as functionality or certain blocks/items? 

Greetings, GhostgamesDHG
